keys:
  # Users
  - &users:
    - &joka DA94A86D7CD8B46E
  # Hosts
  - &hosts:
    - &alcedo age1frx3zkwt6qmnnwq5tz2mvylf7ry7ft4vzahs4ajlzcxx3l45950qc0k40x
    - &hirundo age1uhqk26zf6qn35y745lgqy296nlapdjz2hyazdy2a5yg6mw4303dss96629
    - &falco age1uwlzhmu3pw3rzpjtj5gu07qxge9tvr5vsq4995xxy7d4mtw7cugsh7d709
    - &regulus age1zy59ayt0ex94dzjjued3cgq9294ylu4ynskqhhgmna4jpxup6g0q3j2afq
    - &strix age1nuvx2zd6keg07mjt8n88rxzuavuzs75yzydy477ae6fyg4g4eu4q09k2jz
creation_rules:
  - path_regex: secrets/services/minecraft/secrets.ya?ml$
    key_groups:
      - age:
          - *strix
        pgp:
          - *joka
  - path_regex: secrets/services/auth/secrets.ya?ml$
    key_groups:
      - age:
          - *strix
          - *hirundo
        pgp:
          - *joka
  - path_regex: secrets/services/headscale/secrets.ya?ml$
    key_groups:
      - age:
          - *strix
          - *hirundo
        pgp:
          - *joka
  - path_regex: secrets/services/mosquitto/secrets.ya?ml$
    key_groups:
      - age:
          - *regulus
        pgp:
          - *joka
  - path_regex: secrets/services/hydra/secrets.ya?ml$
    key_groups:
      - age:
          - *strix
        pgp:
          - *joka
  - path_regex: secrets/services/homelab/secrets.ya?ml$
    key_groups:
      - age:
          - *regulus
        pgp:
          - *joka
  - path_regex: secrets/joka/secrets.ya?ml$
    key_groups:
      - age:
          - *alcedo
          - *hirundo
          - *strix
          - *falco
          - *regulus
        pgp:
          - *joka